baseURL = 'https://dnakamura-git.github.io/'
languageCode = 'en-us'
title = 'Daisuke Nakamura'
theme = 'PaperMod'

[params.profileMode]
  enabled = true
  title = "Daisuke Nakamura"
  subtitle = "University of Vienna | Communication Science"
  imageUrl = "images/profile.jpg"

  [[params.socialIcons]]
    name = "bluesky"
    url = "https://bsky.app/profile/daisukenakamura.bsky.social"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/dnakamura-git"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/daisukeh-nakamura/"

  [[params.profileMode.buttons]]
    name = "Lab's Website"
    url = "https://compcommlab.univie.ac.at/"

[[menu.main]]
  identifier = "Bio"
  name = "Bio"
  url = "/Bio/"
  weight = 1

[[menu.main]]
  identifier = "cv"
  name = "CV"
  url = "/cv/"
  weight = 2

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight = 3
